### ISSUE TITLE
Exporting Data

### ISSUE THREAD

**Issue by Channen1221** [GaelleLefort/ASICS#2]
Hi there

First off, thank you for this package! 

However, I seem to be having an issue exporting the data - although R gives me the first few results, it cuts me off owing to space limit (understandable), but i need all the data to do additional statistical analyses. I've tried exporting the quantification results, PCA, OPLSDA, kruskal-wallis results as text files using the common method ("write.table" command).

Error given:

> Error in as.data.frame.default(x[[i]], optional = TRUE) : 
cannot coerce class 'structure("ASICSResults", pacakge = "ASICS") to a data frame

Can you give any direction as to how to export the data?

**Comment by GaelleLefort** [comment]
Hi @Channen1221,
Sorry for the late answer.
You can't directly export ASICS results with write.table as the results isn't a table.

To export ASICS quantifications you can extract quantification with quantif = getQuantification(<name_of_your_results>)  and then write.table(quantif, ....).

For PCA and others, some tables are in <name_of_your_PCAresults>@results (for example for thee loadings : res_pca@results@loadingMN). You can thus export the information you needed with write.table(res_pca@results@loadingMN, ...).

Gaëlle

**Comment by Channen1221** [comment]
Thank you so much this was exactly what I need!
